name: to staging
description: 'rebase main onto develop without force'

branding:
  icon: 'aperture'
  color: 'purple'

inputs:
  app-key:
    description: github app private key
  app-id:
    description: github app id
  app-email:
    description: github app no reply email
  app:
    description: github app name

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - uses: emocional/action-git-config@main
      with:
        app: ${{ inputs.app }}
        app-id: ${{ inputs.app-id }}
        app-email: ${{ inputs.app-email }}
        app-key: ${{ inputs.app-key }}
      id: get_token

    - name: Rebase main onto develop
      shell: sh
      run: |
        git fetch origin develop
        git rebase origin/develop
        git push origin main
